language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - tip

git:
  depth: 1

install:
  - go install -race std
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
  - go get github.com/tools/godep
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - golint .
  - go test -race ./...
  - go test -cover ./...
